### ISSUE TITLE
How to call only the relation classifier on a pair of entities?

### ISSUE THREAD

**Issue by vinhkhuc** [lavis-nlp/spert#55]
Hi,
Thanks for the great work. I plan to use SpERT's relation classifier together with SpaCy's NER. For a given sentence, I can run NER to get entities then I want to use SpERT to find the relations between any two entities.

I wonder if anyone can point me to the code that can do that.
Thanks!

**Comment by celsofranssa** [comment]
Any update on this?

**Comment by markus-eberts** [comment]
Hi,
since SpERT is build for joint entity and relation extraction, the current code is not built to be used for a classification setting (given two entities). In this case, some modifications (especially regarding sampling and model architecture) are required. This is out of scope for this project - however, if you need some help to adjust the code to your needs, feel free to write me an email.
